# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU


S3_ACCESS_KEY: AKIAIDGH5CPGVWNNUKBA
S3_SECRET_ACCESS: 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
S3_REGION: ap-southeast-1
S3_BUCKET: elasticbeanstalk-ap-southeast-1-354987281312

SMTP_USER: AKIAJYD5EW7YL4JGYI3A
SMTP_PASSWORD: AmoSlS/lmi6YSrhaw/PJ+XTEThnccc1+BnRAkGCE3quk
