# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c39fa318596b1105e0269d0054b5c9a057f5a2b5d4ccf09b902f3caca7876e166279fbc28b5e66e75257a1e8e470cfbd46c9edf53271160168e5c6d1c43dcf83

test:
  secret_key_base: 0536a6f7129c5e6b8e8f35aabdc7db464a1e83495e6c0c80b9f6e4a1356214ff26366fb50ae2d62fa43c0d5547ff94a5330460c5530563434b95262b9821d091

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
